version: "3.9"
services:
  pysonet_back:
    build: .
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  pysonet_db:
    image: postgres:12.0-alpine
    volumes:
      - pysonet_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

volumes:
  pysonet_postgres_data:
